export const GET_CREATE_NEW_LIST_SUCCESS = "GET_CREATE_NEW_LIST_SUCCESS";
export const GET_FETCH_LIST_FROM_SERVER_SUCCESS =
  "GET_FETCH_LIST_FROM_SERVER_SUCCESS";
export const GET_ADD_TODO_SUCCESS = "GET_ADD_TODO_SUCCESS";
export const GET_FETCH_TODO_FROM_SERVER_SUCCESS =
  "GET_FETCH_TODO_FROM_SERVER_SUCCESS";
export const GET_DELETE_TODO_SUCCESS = "GET_DELETE_TODO_SUCCESS";
export const GET_HABITS_TODO_SUCCESS = "GET_HABITS_TODO_SUCCESS";
export const CHANGE_THEME = "CHANGE_THEME";
export const GET_PERCENTAGE_TODO_ADD_USER = 'GET_PERCENTAGE_TODO_ADD_USER';
export const GET_RESET_PERCENTAGE_TODO_ADD_USER = 'GET_RESET_PERCENTAGE_TODO_ADD_USER';